version: "2"
services:
  snapcast-client:
    build:
      context: ./snapcast-client
      args:
        SNAPCAST_VERSION: 0.19.0
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - snapcast:/var/cache/snapcast
volumes:
  snapcast:
